# Generated by Django 3.2.9 on 2022-01-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('nombre', models.CharField(max_length=80)),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('numero', models.AutoField(default=1, primary_key=True, serialize=False)),
            ],
        ),
    ]
